### PR TITLE
Refactored code with PSR-1 and PSR-2 code standards

### PR DESCRIPTION
**Pull request by roberto910907**
Using Sensiolabs tool to refactor the code standard.

https://symfony.com/doc/current/contributing/code/standards.html

### CODE REVIEW

**Comment by hoshomoh** [comment]
Good job @roberto910907 Kindly update the README on how to run this on other devs machine to ensure that the set rules are not broken by anyone.

Also, let us update the project build to run a check on the pushed files so as to ensure that all pushed code meet the set standard

**Comment by roberto910907** [comment]
@hoshomoh Sure, I'll update the code and **README** with a new section "Contributing to the Project" explaining what do you have to do for applying the **Coding Standards**.

:+1:

**Comment by hoshomoh** [comment]
@roberto910907 do you know if there is a way of checking if the code passes the setup standard? I'm checking the docs and I can't seem to find anything

**Comment by roberto910907** [comment]
@hoshomoh We could add that verification step into the travisCI config, I'm currently using circleCI in most of my projects and doing something like:

```
      - run:
          name: Code quality (php-cs, phpmd)
          command: |
             OUTPUT_PHPCS=$(echo vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection app tests) | true
             echo "Files that violation rules of phpcs: "
             echo $OUTPUT_PHPCS
             vendor/bin/phpmd app text phpmd.xml --exclude=tests --suffixes=php --ignore-violations-on-exit
```
Using **php_cs.dist** as well as **phpmd** to analyze the code standards rules. I can change the travis configuration to do that.

And also I'll update README with some interesting links about [how to configure these tools in PhpStorm](https://hackernoon.com/how-to-configure-phpstorm-to-use-php-cs-fixer-1844991e521f).

**Comment by hoshomoh** [comment]
Yeah sure feel free to update the TravisCI config so that these checks are performed, since this checks are also commands that anyone can run on their machine, in the **Contributing to the Project section** you are adding, just document what commands should be run before pushing. That should be sufficient

Also since this packages are composer packages that can be installed in the vendor folder, let us add them to the composer file dev section and map those commands to a script say `lint` just as I have `test`, so that would run (php-cs, phpmd) checks

**Comment by roberto910907** [comment]
@hoshomoh Sounds Good. I definitely will work on that this weekend. :+1:

**Comment by hoshomoh** [comment]
@roberto910907 you should try to close this out this weekend 🤝

**Review by hoshomoh — APPROVED** [review]

**Pull request merged**
